# Generated by Django 3.1 on 2020-09-07 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActivityTitle', models.CharField(max_length=150)),
                ('ActivityDescription', models.TextField()),
                ('ActivityMaterial', models.CharField(max_length=250)),
                ('ActivityStartTime', models.DateTimeField()),
                ('ActivityEndTime', models.DateTimeField()),
                ('ActivityPostDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ActivityLocation', models.CharField(max_length=250)),
                ('ActivityAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
