# Generated by Django 3.1 on 2020-09-21 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_date',
        ),
    ]
