# Generated by Django 3.1 on 2020-09-08 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='ActivityAuthor',
            new_name='activity_author',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='ActivityDescription',
            new_name='activity_description',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='ActivityEndTime',
            new_name='activity_end_time',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='ActivityLocation',
            new_name='activity_location',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='ActivityMaterial',
            new_name='activity_material',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='ActivityPostDate',
            new_name='activity_post_date',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='ActivityStartTime',
            new_name='activity_start_time',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='ActivityTitle',
            new_name='activity_title',
        ),
    ]
