# Generated by Django 3.1 on 2020-09-10 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_app', '0002_auto_20200908_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activity'},
        ),
    ]
