# Generated by Django 3.1 on 2020-09-21 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_auto_20200921_0739'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_app', '0002_remove_activity_activity_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_app.activity')),
                ('visitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account_app.visitor')),
            ],
            options={
                'verbose_name_plural': 'Interest',
            },
        ),
        migrations.CreateModel(
            name='VisitorNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='Your RSVP is complete')),
                ('notification_date', models.DateTimeField()),
                ('interest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_app.interest')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'InterestNotifications',
            },
        ),
    ]
