# Generated by Django 3.1 on 2020-09-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_auto_20200910_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='6894736528', max_length=250, null=True),
        ),
    ]
