# Generated by Django 3.1 on 2020-09-21 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account_app', '0004_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='visitor',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
